@startuml
left to right direction

[*] --> ParentState

state ParentState {
    state StateB #LightGreen
    state exit1 <<exitpoint>>
    state exit2 <<exitpoint>> #LightGreen 
    [*] --> StateA
    StateA -up-> StateB
    StateA --> exit1: EVENT_1
    StateB --> exit2: **EVENT_2**
}

state StateD #LightSkyBlue
exit1 --> StateC: ON_EXIT1
exit2 --> StateD: **ON_EXIT2**

@enduml