#!/bin/sh

mkdir ./build
cd ./build

if [ ${PWD##*/} = "build" ]
then
    rm -Rvf ./*
    cmake -DHSMBUILD_TESTS=ON -DHSMBUILD_VERBOSE=OFF -DHSMBUILD_DEBUGGING=OFF -DHSMBUILD_EXAMPLES=OFF  -DHSMBUILD_DISPATCHER_QT=OFF -DHSMBUILD_DISPATCHER_GLIB=OFF -DHSMBUILD_DISPATCHER_GLIBMM=OFF -DHSMBUILD_DISPATCHER_STD=OFF -DHSMBUILD_PLATFORM=FREERTOS -DHSMBUILD_FREERTOS_ROOT=~/projects/FreeRTOS -DHSMBUILD_DISPATCHER_FREERTOS=ON -DHSMBUILD_FREERTOS_DEFAULT_ISR_DETECT=ON ..
    make -j5
fi
