if (HSMBUILD_DISPATCHER_GLIBMM)
    pkg_check_modules(GLIB REQUIRED glib-2.0)
    pkg_check_modules(GLIBMM REQUIRED glibmm-2.4)

    set(HSM_DEFINITIONS_GLIBMM ${HSM_DEFINITIONS_BASE} -DHSM_BUILD_HSMBUILD_DISPATCHER_GLIBMM CACHE STRING "" FORCE)
    add_definitions(-DHSM_BUILD_HSMBUILD_DISPATCHER_GLIBMM)
    add_library(${HSM_LIBRARY_NAME}_glibmm STATIC ${CMAKE_CURRENT_SOURCE_DIR}/src/HsmEventDispatcherGLibmm.cpp)
    target_include_directories(${HSM_LIBRARY_NAME}_glibmm PUBLIC ${GLIB_INCLUDE_DIRS} ${GLIBMM_INCLUDE_DIRS})
    target_compile_options(${HSM_LIBRARY_NAME}_glibmm PUBLIC "-fPIC")

    # Export variables
    set(HSMCPP_GLIBMM_CXX_FLAGS ${HSMCPP_CXX_FLAGS} CACHE STRING "" FORCE)
    set(HSMCPP_GLIBMM_LIB ${HSM_LIBRARY_NAME}_glibmm ${HSMCPP_LIB} ${GLIB_LDFLAGS} ${GLIBMM_LDFLAGS} CACHE STRING "" FORCE)
    set(HSMCPP_GLIBMM_INCLUDE ${HSMCPP_INCLUDE} ${GLIB_INCLUDE_DIRS} ${GLIBMM_INCLUDE_DIRS} CACHE STRING "" FORCE)
endif()