pkg_check_modules(HSMCPP_GLIBMM REQUIRED hsmcpp_glibmm)

set(HSMCPP_INCLUDE_DIRS ${HSMCPP_INCLUDE_DIRS} ${HSMCPP_GLIBMM_INCLUDE_DIRS})
set(HSMCPP_LDFLAGS ${HSMCPP_LDFLAGS} ${HSMCPP_GLIBMM_LDFLAGS})
set(HSMCPP_CFLAGS_OTHER ${HSMCPP_CFLAGS_OTHER} ${HSMCPP_GLIBMM_CFLAGS_OTHER})