pkg_check_modules(HSMCPP_STD REQUIRED hsmcpp_std)

set(HSMCPP_INCLUDE_DIRS ${HSMCPP_INCLUDE_DIRS} ${HSMCPP_STD_INCLUDE_DIRS})
set(HSMCPP_LDFLAGS ${HSMCPP_LDFLAGS} ${HSMCPP_STD_LDFLAGS})
set(HSMCPP_CFLAGS_OTHER ${HSMCPP_CFLAGS_OTHER} ${HSMCPP_STD_CFLAGS_OTHER})