pkg_check_modules(HSMCPP_GLIB REQUIRED hsmcpp_glib)

set(HSMCPP_INCLUDE_DIRS ${HSMCPP_INCLUDE_DIRS} ${HSMCPP_GLIB_INCLUDE_DIRS})
set(HSMCPP_LDFLAGS ${HSMCPP_LDFLAGS} ${HSMCPP_GLIB_LDFLAGS})
set(HSMCPP_CFLAGS_OTHER ${HSMCPP_CFLAGS_OTHER} ${HSMCPP_GLIB_CFLAGS_OTHER})