name: "Deploy ArduinoIDE library"

on:
  workflow_dispatch:
  workflow_run:
    workflows: [Build]
    branches: [main]
    types: [completed]

jobs:
  check-hsmcpp-version:
    if: ${{ (github.repository == 'igor-krechetov/hsmcpp') && ((github.event.workflow_run == null) || ((github.event.workflow_run.conclusion == 'success') && (github.event.workflow_run.event == 'push'))) }}
    runs-on: ubuntu-latest
    outputs:
      commit_version: ${{ steps.get_version.outputs.commit_version }}
      commit_action: ${{ steps.get_version.outputs.commit_action }}
      commit_sha: ${{ steps.commit_sha.outputs.value }}
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/workflows/get-commit-version
        id: get_version
        with:
          repo_dir: ${{ env.GITHUB_WORKSPACE }}
          commit_sha: ${{ github.event.workflow_run.head_sha }}
      - id: commit_sha
        run: echo "value=${{ github.event.workflow_run.head_sha || github.sha }}" >> "$GITHUB_OUTPUT"

  deploy:
    needs: check-hsmcpp-version
    if: ${{ needs.check-hsmcpp-version.outputs.commit_version != '' }}
    uses: igor-krechetov/hsm-github-workflows/.github/workflows/deploy.yml@main
    with:
      deploy_target: arduinoide
      commit_sha: ${{ needs.check-hsmcpp-version.outputs.commit_sha }}
      commit_version: ${{ needs.check-hsmcpp-version.outputs.commit_version }}
      commit_action: ${{ needs.check-hsmcpp-version.outputs.commit_action }}
      target_repo: igor-krechetov/hsmcpp-arduinoide
      target_branch: main
      publish_registry: false
    secrets: inherit
