name: Deploy - PlatformIO - Arduino

# Start only after Build was finished
on:
  workflow_run:
    workflows: ["Build"]
    types:
      - completed

jobs:
  deploy-platformio-arduino:
    # based on: https://github.com/orgs/community/discussions/26238
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    runs-on: ubuntu-latest

    env:
      target_dir: './test_actions/'

    steps:
    - uses: actions/checkout@v3
      with:
        ref: main
        path: './main'
    - uses: actions/checkout@v3
      with:
        ref: test_actions
        path: ${{ env.target_dir }}
    - name: Import GPG key
      id: import_gpg
      uses: crazy-max/ghaction-import-gpg@v5
      with:
        gpg_private_key: ${{ secrets.BOT_GPG_PRIVATE_KEY }}
        passphrase: ${{ secrets.BOT_GPG_PASSPHRASE }}
        git_config_global: true
        git_user_signingkey: true
        git_commit_gpgsign: true
        workdir: ${{ env.target_dir }}
    - name: Generate package
      run: |
        cmake -S ./main -B ./main/build -DHSMBUILD_TARGET=package -DHSMBUILD_PLATFORM=arduino
        cmake --build ./main/build --target install
    - name: Copy package to target repository
      run: |
        cp -Rv ./main/build/deploy/* "$target_dir"
    - name: Copy other files
      run: |
        cp ./main/README.md "$target_dir"
        cp ./main/CHANGELOG.md "$target_dir"
        cp ./main/LICENSE "$target_dir"
    - name: Commit new files
      run: |
        cd "$target_dir"
        git add -A
        git commit -S -am "Deployment test ${{ github.event.inputs.name }}"
        git push
